name: Update HDNEA from Direct API in Browser

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Fetch HDNEA from Your API URL in Browser
        run: |
          node -e "
          const fs = require('fs');
          const puppeteer = require('puppeteer');

          (async () => {
            let browser;
            try {
              console.log('Launching browser...');
              browser = await puppeteer.launch({
                headless: true,
                args: [
                  '--no-sandbox',
                  '--disable-setuid-sandbox',
                  '--disable-web-security',
                  '--disable-features=IsolateOrigins,site-per-process'
                ]
              });

              const page = await browser.newPage();

              // Set headers
              await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36');
              await page.setExtraHTTPHeaders({
                'Origin': 'https://www.sonyliv.com',
                'Referer': 'https://www.sonyliv.com/',
                'Accept': 'application/json',
                'Accept-Language': 'en-US,en;q=0.9'
              });

              console.log('Directly calling your API in browser...');
              const response = await page.evaluate(async () => {
                const res = await fetch('https://apiv2.sonyliv.com/AGL/4.7/A/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1090492858', {
                  headers: {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    'Origin': 'https://www.sonyliv.com',
                    'Referer': 'https://www.sonyliv.com/',
                    'Accept': 'application/json'
                  }
                });
                const data = await res.json();
                return { status: res.status, body: data };
              });

              if (response.status !== 200) {
                throw new Error('API failed with status: ' + response.status);
              }

              const videoURL = response.body?.resultObj?.videoURL;
              if (!videoURL) {
                throw new Error('videoURL not found in response');
              }

              const hdneaMatch = videoURL.match(/hdnea=([^&]+)/);
              if (!hdneaMatch) {
                throw new Error('HDNEA token not found in videoURL');
              }

              const token = decodeURIComponent(hdneaMatch[1]);

              // Update JSON file
              if (!fs.existsSync('Slivtv.json')) {
                throw new Error('Slivtv.json not found');
              }

              const json = JSON.parse(fs.readFileSync('Slivtv.json', 'utf8'));
              const channel = json.find(ch => ch.name === 'Sony SAB HD');
              if (!channel?.link) {
                throw new Error('Sony SAB HD channel not found');
              }

              channel.link = channel.link.replace(/hdnea=[^&]+/, 'hdnea=' + encodeURIComponent(token));
              fs.writeFileSync('Slivtv.json', JSON.stringify(json, null, 2));

              console.log('HDNEA Token Updated Successfully!');
              console.log('Token (first 60):', token.substring(0, 60) + '...');

            } catch (err) {
              console.error('Failed:', err.message);
              process.exit(1);
            } finally {
              if (browser) await browser.close();
            }
          })();
          "

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Slivtv.json
          git commit -m "Update HDNEA from direct API in browser" || echo "No change"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
