name: Update SlivTV Cookies

on:
  schedule:
    # Har 6 ghante mein chalega (aap badal sakte hain)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Manual trigger bhi allowed

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Download & Extract hdnea Cookie
        id: extract_cookie
        run: |
          API_URL="https://apiv4.sonyliv.com/AGL/4.7/A/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1000051729"
          RESPONSE=$(curl -s "$API_URL")
          
          # Extract hdnea parameter
          HDNEA=$(echo "$RESPONSE" | grep -o 'hdnea=[^"]*' | head -1)
          
          if [ -z "$HDNEA" ]; then
            echo "❌ hdnea not found in API response"
            exit 1
          fi
          
          echo "✅ Found hdnea: $HDNEA"
          echo "HDNEA=$HDNEA" >> $GITHUB_OUTPUT

      - name: Update Slivtv.json with New Cookie
        run: |
          HDNEA="${{ steps.extract_cookie.outputs.HDNEA }}"
          FILE="Slivtv.json"
          
          if [ ! -f "$FILE" ]; then
            echo "❌ $FILE not found!"
            exit 1
          fi
          
          # Backup original
          cp "$FILE" "$FILE.bak"
          
          # Replace hdnea in all links
          sed -i "s|hdnea=[^&\"']*|${HDNEA}|g" "$FILE"
          
          echo "✅ Updated $FILE with new hdnea"

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add Slivtv.json
          git commit -m "🔄 Auto-update hdnea cookie in Slivtv.json" || echo "No changes to commit"
          git push
