name: Update SonyLIV hdnea (Auto Indian Proxy)

on:
  schedule:
    - cron: '0 */3 * * *'   # Har 3 ghante mein
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Working Indian Proxy
        id: proxy
        run: |
          echo "Downloading fresh Indian proxies..."
          PROXY_LIST=$(curl -s "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt")
          
          # Filter India proxies (IN) and test first 5
          INDIAN_PROXIES=$(echo "$PROXY_LIST" | grep -i "IN" | head -5)
          
          WORKING_PROXY=""
          for PROXY in $INDIAN_PROXIES; do
            echo "Testing proxy: $PROXY"
            if curl -s --proxy "$PROXY" --max-time 10 "https://httpbin.org/ip" | grep -q "origin"; then
              WORKING_PROXY="$PROXY"
              echo "Working proxy found: $PROXY"
              break
            fi
          done
          
          if [ -z "$WORKING_PROXY" ]; then
            echo "No working Indian proxy found!"
            exit 1
          fi
          
          echo "PROXY=$WORKING_PROXY" >> $GITHUB_OUTPUT

      - name: Fetch hdnea via Working Proxy
        id: fetch
        run: |
          PROXY="${{ steps.proxy.outputs.PROXY }}"
          API_URL="https://apiv4.sonyliv.com/AGL/4.7/A/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1000051729"

          echo "Using proxy: $PROXY"
          RESPONSE=$(curl -s --proxy "$PROXY" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Referer: https://www.sonyliv.com/" \
            "$API_URL")

          echo "$RESPONSE" > debug.json

          if echo "$RESPONSE" | grep -q "EPDblocked"; then
            echo "Proxy blocked by SonyLIV!"
            cat debug.json
            exit 1
          fi

          VIDEO_URL=$(echo "$RESPONSE" | grep -o '"videoURL":"[^"]*' | cut -d'"' -f4)
          if [ -z "$VIDEO_URL" ]; then
            echo "videoURL not found!"
            exit 1
          fi

          HDNEA=$(echo "$VIDEO_URL" | grep -o 'hdnea=[^& ]*')
          if [ -z "$HDNEA" ]; then
            echo "hdnea not found!"
            exit 1
          fi

          echo "HDNEA=$HDNEA" >> $GITHUB_OUTPUT

      - name: Update Slivtv.json
        run: |
          HDNEA="${{ steps.fetch.outputs.HDNEA }}"
          FILE="Slivtv.json"
          
          cp "$FILE" "$FILE.bak"
          sed -i "s|hdnea=[^&\"' ]*|${HDNEA}|g" "$FILE"
          echo "Updated $FILE"

      - name: Commit & Push
        run: |
          git add Slivtv.json
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto-update hdnea (Indian proxy)"
            git push
          fi
