name: Update HDNEA Token with Play Click

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer + Axios
        run: |
          npm install puppeteer axios

      - name: Get HDNEA by Clicking Play Button
        run: |
          node -e "
          const fs = require('fs');
          const puppeteer = require('puppeteer');
          const axios = require('axios');

          (async () => {
            let browser;
            try {
              console.log('Launching stealth browser...');
              browser = await puppeteer.launch({
                headless: true,
                args: [
                  '--no-sandbox',
                  '--disable-setuid-sandbox',
                  '--disable-web-security',
                  '--disable-features=IsolateOrigins,site-per-process',
                  '--disable-blink-features=AutomationControlled',
                  '--start-maximized'
                ],
                defaultViewport: null
              });

              const page = await browser.newPage();

              // Hide automation
              await page.evaluateOnNewDocument(() => {
                Object.defineProperty(navigator, 'webdriver', { get: () => false });
                window.chrome = { runtime: {} };
                Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
                Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3] });
              });

              await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36');

              // Block images, fonts, etc.
              await page.setRequestInterception(true);
              page.on('request', (req) => {
                const type = req.resourceType();
                if (['image', 'stylesheet', 'font', 'media'].includes(type)) {
                  req.abort();
                } else {
                  req.continue();
                }
              });

              console.log('Opening Sony SAB Live...');
              await page.goto('https://www.sonyliv.com/live-tv/sab-tv-live-1000004996', {
                waitUntil: 'networkidle2',
                timeout: 30000
              });

              // Wait for Play Button
              console.log('Waiting for Play button...');
              await page.waitForSelector('button.play-button, button[aria-label=\"Play\"], .play-icon', { 
                timeout: 15000 
              });

              // Click Play
              console.log('Clicking Play button...');
              await page.click('button.play-button, button[aria-label=\"Play\"], .play-icon');

              // Wait for API
              console.log('Waiting for VIDEOURL API...');
              const response = await page.waitForResponse(res => 
                res.url().includes('VIDEOURL/VOD/1090492858') && 
                res.status() === 200,
                { timeout: 20000 }
              );

              const data = await response.json();
              const videoURL = data.resultObj?.videoURL;
              if (!videoURL) throw new Error('videoURL missing');

              const hdneaMatch = videoURL.match(/hdnea=([^&\"']+)/);
              if (!hdneaMatch) throw new Error('HDNEA token not found');

              const token = decodeURIComponent(hdneaMatch[1]);

              // Update JSON
              if (!fs.existsSync('Slivtv.json')) throw new Error('Slivtv.json not found');
              const json = JSON.parse(fs.readFileSync('Slivtv.json', 'utf8'));
              const channel = json.find(ch => ch.name === 'Sony SAB HD');
              if (!channel?.link) throw new Error('Channel not found');

              channel.link = channel.link.replace(/hdnea=[^&]+/, 'hdnea=' + encodeURIComponent(token));
              fs.writeFileSync('Slivtv.json', JSON.stringify(json, null, 2));

              console.log('HDNEA Token Updated Successfully!');
              console.log('Token preview:', token.substring(0, 60) + '...');

            } catch (err) {
              console.error('Failed:', err.message);
              process.exit(1);
            } finally {
              if (browser) await browser.close();
            }
          })();
          "

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Slivtv.json
          git commit -m "Update HDNEA via Play button click" || echo "No change"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
