name: Update HDNEA Token in Slivtv.json

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios https-proxy-agent

      - name: Fetch and update HDNEA token
        run: |
          node -e "
          const fs = require('fs');
          const axios = require('axios');
          const HttpsProxyAgent = require('https-proxy-agent');

          const proxyHost = '${{ secrets.PROXY_HOST }}';
          const proxyPort = '${{ secrets.PROXY_PORT }}';
          const proxyUser = '${{ secrets.PROXY_USER }}';
          const proxyPass = '${{ secrets.PROXY_PASS }}';

          const proxyUrl = `http://${proxyUser}:${proxyPass}@${proxyHost}:${proxyPort}`;
          const agent = new HttpsProxyAgent(proxyUrl);

          async function updateToken() {
            try {
              if (!fs.existsSync('Slivtv.json')) throw new Error('File not found');

              const json = JSON.parse(fs.readFileSync('Slivtv.json', 'utf8'));
              if (!Array.isArray(json)) throw new Error('Invalid JSON format');

              const channel = json.find(ch => ch.name === 'Sony SAB HD');
              if (!channel?.link) throw new Error('Channel not found');

              const res = await axios.get(
                'https://apiv2.sonyliv.com/AGL/4.7/A/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1090492858',
                {
                  headers: {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                    'Origin': 'https://www.sonyliv.com',
                    'Referer': 'https://www.sonyliv.com/',
                    'Accept-Language': 'en-US,en;q=0.9'
                  },
                  httpsAgent: agent,
                  timeout: 15000
                }
              );

              const url = res.data.resultObj?.videoURL;
              if (!url) throw new Error('videoURL missing');

              const hdnea = url.match(/hdnea=([^&]+)/)?.[1];
              if (!hdnea) throw new Error('Token not found');

              const token = decodeURIComponent(hdnea);
              channel.link = channel.link.replace(/hdnea=[^&]+/, 'hdnea=' + encodeURIComponent(token));

              fs.writeFileSync('Slivtv.json', JSON.stringify(json, null, 2));
              console.log('Updated HDNEA token');
            } catch (err) {
              console.error('Failed:', err.message);
              process.exit(1);
            }
          }
          updateToken();
          "

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Slivtv.json
          git commit -m "Update HDNEA token" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
